name: "Wild Care"
tagline: "Verein für soziale Praxis"
url: "https://wildcare.space"
defaultOgImage: "/assets/images/og-default.jpg"
email: "hello@wildcare.space"
instagram: "https://instagram.com/wildcare.space"
copyrightYear: 2026
defaultLocale: "de"
